server:
    port: 8080
    contextPath: /rpsp

spring:
    profiles:
        active: dev

    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:~/test2.h2.db;DB_CLOSE_DELAY=-1
        databaseName:
        serverName:
        username:
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
             hibernate.cache.use_second_level_cache: false
             hibernate.cache.use_query_cache: false
             hibernate.generate_statistics: false
             hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080

#    thymeleaf:
#        mode: XHTML
#        cache: false
#        viewNames: error

metrics:
    jmx.enabled: false
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: curt

#cache:
#    timeToLiveSeconds: 3600
#    ehcache:
#        maxBytesLocalHeap: 16M


rpsp:
  admin:
    login: admin@system
    password: 123
